### ISSUE TITLE
Strange behaviour on iPad

### ISSUE THREAD

**Issue by diniska** [kean/ThreeColumnNavigation#3]
iPadOS 14 simulator.

The initial state for iPad is empty:

![Screenshot 1](https://user-images.githubusercontent.com/2674368/121191007-ebbf9c80-c8ae-11eb-9dbb-760a606e8f0b.png)

When I tap the sidebar button. It selects the first row and shows the content.

![Screenshot 2](https://user-images.githubusercontent.com/2674368/121191192-17428700-c8af-11eb-9978-004941b8cb92.png)

This doesn't look right and could be a bit confusing to a user.

![2021-06-08 в 23 16 07 2021-06-08 23_16_54](https://user-images.githubusercontent.com/2674368/121191797-a5b70880-c8af-11eb-860b-13b0aa6bbb61.gif)

Do you know if this issue could be fixed?

**Comment by kean** [comment]
> Do you know if this issue could be fixed?

I would suggest trying to find a workaround by getting access to the underlying UISplitViewController.

**Comment by diniska** [comment]
Thanks! Do you think that workaround could live in this repo for others to use, or you'd rather keep the code clean as is? I'm happy to create a pull request with the workaround.

**Comment by kean** [comment]
I could merge an MR if you open one. To be honest, I needed a solution for macOS and it does work for me on macOS in [Pulse](https://kean.blog/pulse/home). iPadOS is rough, I haven't focused on it at all.

**Comment by diniska** [comment]
Thanks. It works great for macOS.

I've just created the pull request: https://github.com/kean/ThreeColumnNavigation/pull/4

Please, let me know your thoughts about that when you have time.

**Comment by diniska** [comment]
The pull request has been merged. I'll close the issue as I believe that was the best we can do at the moment
